### ISSUE TITLE
ktbs:hasSubject is required

### ISSUE THREAD

**Issue by StatelessCat** [ktbs/ktbs#47]
In the [kTBS documentation](http://kernel-for-trace-based-systems.readthedocs.org/en/v0.4/tutorials/rest-turtle.html#add-obsels-to-trace) the first POST trace example (on a kTBS 0.4 installed via PIP) lead to:

```
403 Forbidden

403 Forbidden - Invalid data
check_new_graph: ko
* Property <http://liris.cnrs.fr/silex/2009/ktbs#hasSubject> of <http://localhost:8001/base1/t01/obs43> should have at least 1 objects; it only has 0
```

It's like `<t01/> :hasDefaultSubject "me" .` doesn't behave as we would expect.
Maybe this should be explained in the documentation ?
Thanks

**Comment by StatelessCat** [comment]
@fconil , As you suggest it, this behavior is only noticed on the [kTBS 0.4 available on Pypi](https://pypi.python.org/pypi/kTBS). 
In the development version, the issue no longer exist.

**Comment by pchampin** [comment]
Indeed, this requirement was present in v0.4, and was dropped latter, so the tutorial has been updated.

Note that different versions of the documentation are available, so if you are using the latest stable release from PyPI, you should use [the *stable* branch of the tutorial](http://kernel-for-trace-based-systems.readthedocs.io/en/stable/tutorials/rest-turtle.html).

But it is true that the README points to the *develop* branch, and both make sense, depending on the context...
