### ISSUE TITLE
Being able to refresh a @stats graph even on a Stored Trace

### ISSUE THREAD

**Issue by fconil** [ktbs/ktbs#53]
It would be useful to be able to refresh a @stats graph even on Stored Traces.

Despite the use for kTBS developpers, it could be necessary if we add some new statistics.

**Comment by pchampin** [comment]
What happens when you try try ``@stats?refresh=yes``?

**Comment by fconil** [comment]
404 Not Found - Invalid parameters
Unsupported parameter(s):refresh

**Comment by pchampin** [comment]
Seems to be fixed now, probably with 362ecfa9
