### ISSUE TITLE
Incorrect paths to parent resource from nested bases

### ISSUE THREAD

**Issue by hsaladin** [ktbs/ktbs#78]
When performing a GET request to the URI of a base which is itself contained in a parent base, the returned data always contains : 

> "inRoot": "../"

which is wrong because "../" is the URI of a base, not a root, and the top-level parent root should be at "../../" or maybe even "../../../" etc ... depending of the number of levels of base-nesting.

This makes it impossible to determine where exactly the resource resides in the root's object hierarchy or what type of resource is the parent object ... unless we perform GET requests for every parent resource until we hit the root, which would be inefficient.

Example : https://liris-ktbs01.insa-lyon.fr:8000/public/master-ia-2018/CASSAN_VERKUN_PISTER_TEITGEN_COTTET/CASSAN_VERKIN_PISTER_TEITGEN_COTTET/

In this example (which is a base, in a base, in a base !), the data should rather contain :

at least

> "inBase": "../"

or maybe 

> "inBase": "../"
> "inRoot": "../../../"

or maybe even :

> "inBase": "../"
> "inBase": "../../"
> "inRoot": "../../../"

**Comment by pchampin** [comment]
I'm not sure yet how the property will be named (I may rename "inBase" and "inRoot" altogether into something more neutral). But one thing is for sure: a base (or any other element, for that matter) will only point to its immediate parent. You will have to recursively "climb up" to find the root, if you need to.

**Comment by hsaladin** [comment]
OK, that's totally fine.

**Comment by pchampin** [comment]
The problem is actually not with the JSON-LD serializer (which knows when to use `inRoot` and `inBase`), but with the JSON parser, which sometimes puts *both* in a subbase (and `inRoot` takes precedence in the serializer).
